version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install saas
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            source ~/.profile
            npm install -g node-sass aws-cli
            node-sass scss/ -o css/
            rm -rf scss/
      - run:
          name: Sync functions to S3 Bucket
          command: "~/.local/bin/aws s3 sync . s3://$S3_BUCKET --delete"

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
